name: konverti prezentaĵon al filmo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  konverto:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ffmpeg libreoffice-impress imagemagick
      - run: sudo sed -i '/policy.*domain.*coder.*rights.*none.*pattern.*PDF/d' /etc/ImageMagick-6/policy.xml
      - run: make
      - run: find .

