name: konverti prezentaĵon al filmo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  konverto:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ffmpeg default-jre libreoffice-java-common libreoffice-impress ghostscript
      - run: sudo sed -i 's/^\(.*policy.*domain.*coder.*rights.*\)none\(.*pattern.*PDF.*\)$/\1read|write\2/' /etc/ImageMagick-6/policy.xml
      - run: cat /etc/ImageMagick-6/policy.xml
      - run: make
      - run: mkdir info-beamer
      - run: mv Esperanto.mp4 info-beamer/
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'info-beamer'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
